PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?programminglanguage ?label
WHERE {
        ?programminglanguage wdt:P31 wd:Q9143.
        ?programminglanguage rdfs:label ?label.
        FILTER(lang(?label) = "en").
}
LIMIT 100
