#title: Programming paradigm identifiers of programming languages

SELECT DISTINCT ?proglang (GROUP_CONCAT(DISTINCT ?paradigm_id; SEPARATOR = ", ") AS ?paradigms) 
WHERE 
{ 
  ?proglang wdt:P3966 ?paradigm.
  BIND(REPLACE(STR(?paradigm), "http://www.wikidata.org/entity/", "") as ?paradigm_id)
}
GROUP BY ?proglang
